New single marker combo endpiont
ceresimaging/image-tiler pull request #64
Opened 2020-12-04 18:49 UTC by thetomcraig

2020-12-07 18:12 UTC, maurimiranda requested changes
Looks pretty good, just need a small change to remove a useless parameter in `buildMarkerQuery`. I'll wait for the changes to the marker style before approving.

2020-12-07 18:12 UTC, maurimiranda commented on middlewares/marker.js
> +const buildMarkerQuery = (imagery, marker) => {
Seems like `imagery` param is not used

2020-12-07 19:15 UTC, maurimiranda requested changes
There are a few lint errors to fix. You can see them running `./npm-run lint`

2020-12-07 20:18 UTC, thetomcraig commented on styles/marker-hole.xml
> +</Map>
This is kind of duplicative, but I was afraid to break the existing logic and styles for the issue markers; see comment in the routes file.

2020-12-07 20:21 UTC, thetomcraig commented on middlewares/marker.js
> +    }
@maurimiranda this logic is kind of confusing now imho.  I'm not sure why we are applying the issue style if the user is `SUPPORT_USER`, but this logic will have that take precedence over the `(flight)` check... This can be problematic, as the issue marker stylesheet only renders if the `category` is `issue`.  Do you have context on this user check?  Wondering if we should check `(flight)` first, then check the `user`.

2020-12-16 14:12 UTC, maurimiranda approved these changes

2020-12-16 14:13 UTC, merged